# Generated by Django 2.0.13 on 2019-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteId', models.IntegerField()),
                ('paramTime', models.DateTimeField()),
                ('paramType', models.CharField(max_length=20)),
                ('data', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
