# Generated by Django 2.0.13 on 2019-07-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=40)),
                ('siteEast', models.CharField(max_length=20)),
                ('siteWest', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='paraminfo',
            name='siteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probeData.SiteInfo'),
        ),
    ]
