# Generated by Django 2.0.13 on 2019-07-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0003_siteinfo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='category',
        ),
    ]
