# Generated by Django 2.0.13 on 2019-07-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0004_remove_siteinfo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warningTime', models.DateTimeField()),
                ('warningType', models.CharField(max_length=20)),
                ('warningParam', models.CharField(max_length=20)),
                ('warningValue', models.FloatField()),
                ('limitValue', models.FloatField()),
                ('siteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probeData.SiteInfo')),
            ],
        ),
    ]
