# Generated by Django 2.0.13 on 2019-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0005_warninginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='warninginfo',
            name='isHandle',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
