# Generated by Django 2.0.13 on 2019-07-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0006_warninginfo_ishandle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warninginfo',
            old_name='warningTime',
            new_name='time',
        ),
    ]
