# Generated by Django 2.0.13 on 2019-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0007_auto_20190730_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='info',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='siteinfo',
            old_name='siteEast',
            new_name='siteLat',
        ),
        migrations.RenameField(
            model_name='siteinfo',
            old_name='siteWest',
            new_name='siteLng',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
