# Generated by Django 2.0.13 on 2019-08-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0008_auto_20190808_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgenPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=20)),
                ('siteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probeData.SiteInfo')),
            ],
        ),
    ]
