# Generated by Django 2.0.13 on 2019-08-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probeData', '0009_urgenperson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrgenPerson',
            new_name='UrgentPerson',
        ),
    ]
